//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rentals.Resources.Resource_TestData", typeof(Resource_TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com/pg/brochure/v4/?p=.
        /// </summary>
        internal static string AlgeriaArabicPgUrl {
            get {
                return ResourceManager.GetString("AlgeriaArabicPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.dz/pg/brochure/v4/?p=.
        /// </summary>
        internal static string AlgeriaFrenchPgUrl {
            get {
                return ResourceManager.GetString("AlgeriaFrenchPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.ar/pg/brochure/v4/?p=.
        /// </summary>
        internal static string ArgentinaPgUrl {
            get {
                return ResourceManager.GetString("ArgentinaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.co.at/pg/brochure/v4/?p=.
        /// </summary>
        internal static string AustriaPgUrl {
            get {
                return ResourceManager.GetString("AustriaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.be/nl/pg/brochure/v4/?p=.
        /// </summary>
        internal static string BelgiumDutchPgUrl {
            get {
                return ResourceManager.GetString("BelgiumDutchPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.be/fr/pg/brochure/v4/?p=.
        /// </summary>
        internal static string BelgiumFrenchPgUrl {
            get {
                return ResourceManager.GetString("BelgiumFrenchPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.br/pg/brochure/v4/?p=.
        /// </summary>
        internal static string BrazilPgUrl {
            get {
                return ResourceManager.GetString("BrazilPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com/cafr/pg/brochure/v4/?p=.
        /// </summary>
        internal static string CanadaFrPgUrl {
            get {
                return ResourceManager.GetString("CanadaFrPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com/ca/pg/brochure/v4/?p=.
        /// </summary>
        internal static string CanadaPgUrl {
            get {
                return ResourceManager.GetString("CanadaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChilePgUrl {
            get {
                return ResourceManager.GetString("ChilePgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.cn/pg/brochure/v4/?p=.
        /// </summary>
        internal static string ChinaPgUrl {
            get {
                return ResourceManager.GetString("ChinaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.ef.com.co/pg/brochure/v4/?p=ilc.
        /// </summary>
        internal static string ColombiaPgUrl {
            get {
                return ResourceManager.GetString("ColombiaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com/ca/pg/brochure/v4/?p=.
        /// </summary>
        internal static string CroatiaPgUrl {
            get {
                return ResourceManager.GetString("CroatiaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef-czech.cz/pg/brochure/v4/?p=.
        /// </summary>
        internal static string CzechRepublicPgUrl {
            get {
                return ResourceManager.GetString("CzechRepublicPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef-danmark.dk/pg/brochure/v4/?p=.
        /// </summary>
        internal static string DenmarkPgUrl {
            get {
                return ResourceManager.GetString("DenmarkPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.ec/pg/brochure/v4/?p=.
        /// </summary>
        internal static string EcuadorPgUrl {
            get {
                return ResourceManager.GetString("EcuadorPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com/pg/brochure/v4/?p=.
        /// </summary>
        internal static string EstoniaPgUrl {
            get {
                return ResourceManager.GetString("EstoniaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Url.
        /// </summary>
        internal static string FinlandPgUrl {
            get {
                return ResourceManager.GetString("FinlandPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com/pg/brochure/v4/?p=.
        /// </summary>
        internal static string FinlandSwedPgUrl {
            get {
                return ResourceManager.GetString("FinlandSwedPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.fr/pg/brochure/v4/?p=.
        /// </summary>
        internal static string FrancePgUrl {
            get {
                return ResourceManager.GetString("FrancePgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.de/pg/brochure/v4/?p=.
        /// </summary>
        internal static string GermanyPgUrl {
            get {
                return ResourceManager.GetString("GermanyPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com/ca/pg/brochure/v4/?p=.
        /// </summary>
        internal static string GreecePgUrl {
            get {
                return ResourceManager.GetString("GreecePgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.hk/pg/brochure/v4/?p=.
        /// </summary>
        internal static string HongKongPgUrl {
            get {
                return ResourceManager.GetString("HongKongPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.co.hu/pg/brochure/v4/?p=.
        /// </summary>
        internal static string HungaryPgUrl {
            get {
                return ResourceManager.GetString("HungaryPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef-ireland.ie/pg/brochure/v4/?p=.
        /// </summary>
        internal static string IrelandPgUrl {
            get {
                return ResourceManager.GetString("IrelandPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.kz/pg/brochure/v4/?p=.
        /// </summary>
        internal static string KazakhstanPgUrl {
            get {
                return ResourceManager.GetString("KazakhstanPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.co.kr/pg/brochure/v4/?p=.
        /// </summary>
        internal static string KoreaPgUrl {
            get {
                return ResourceManager.GetString("KoreaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.ly/fp/brochure/v4/?p=.
        /// </summary>
        internal static string LipyaPgUrl {
            get {
                return ResourceManager.GetString("LipyaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.efswiss.ch/de/pg/brochure/v4/?p=.
        /// </summary>
        internal static string LitchensteinPgUrl {
            get {
                return ResourceManager.GetString("LitchensteinPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef-luxemburg.lu/pg/brochure/v4/?p=.
        /// </summary>
        internal static string LuxembourgPgUrl {
            get {
                return ResourceManager.GetString("LuxembourgPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.hk/pg/brochure/v4/?p=.
        /// </summary>
        internal static string MacauPgUrl {
            get {
                return ResourceManager.GetString("MacauPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.mx/pg/brochure/v4/?p=.
        /// </summary>
        internal static string MexicoPgUrl {
            get {
                return ResourceManager.GetString("MexicoPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.nl/pg/brochure/v4/?p=.
        /// </summary>
        internal static string NetherlandsPgUrl {
            get {
                return ResourceManager.GetString("NetherlandsPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.no/fp/brochure/v4/?p=.
        /// </summary>
        internal static string NewZealandPgUrl {
            get {
                return ResourceManager.GetString("NewZealandPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NorwayPgUrl {
            get {
                return ResourceManager.GetString("NorwayPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.pa/pg/brochure/v4/?p=.
        /// </summary>
        internal static string PanamaPgUrl {
            get {
                return ResourceManager.GetString("PanamaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.pe/pg/brochure/v4/?p=.
        /// </summary>
        internal static string PeruPgUrl {
            get {
                return ResourceManager.GetString("PeruPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PolandPgUrl {
            get {
                return ResourceManager.GetString("PolandPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PortugalPgUrl {
            get {
                return ResourceManager.GetString("PortugalPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RussiaPgUrl {
            get {
                return ResourceManager.GetString("RussiaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaudiArabiaArabicPgUrl {
            get {
                return ResourceManager.GetString("SaudiArabiaArabicPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com/pg/brochure/v4/?p=.
        /// </summary>
        internal static string SaudiArabiaEnglishPgUrl {
            get {
                return ResourceManager.GetString("SaudiArabiaEnglishPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SingaporePgUrl {
            get {
                return ResourceManager.GetString("SingaporePgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SlovakiaPgUrl {
            get {
                return ResourceManager.GetString("SlovakiaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SlovenijaPgUrl {
            get {
                return ResourceManager.GetString("SlovenijaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.es/pg/brochure/v4/?p=.
        /// </summary>
        internal static string SpainPgUrl {
            get {
                return ResourceManager.GetString("SpainPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SwedenPgUrl {
            get {
                return ResourceManager.GetString("SwedenPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.efswiss.ch/fr/pg/brochure/v4/?p=.
        /// </summary>
        internal static string SwitzerlandFrenchPgUrl {
            get {
                return ResourceManager.GetString("SwitzerlandFrenchPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.efswiss.ch/de/pg/brochure/v4/?p=.
        /// </summary>
        internal static string SwitzerlandGermanyPgUrl {
            get {
                return ResourceManager.GetString("SwitzerlandGermanyPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.efswiss.ch/it/pg/brochure/v4/?p=.
        /// </summary>
        internal static string SwitzerlandItalianPgUrl {
            get {
                return ResourceManager.GetString("SwitzerlandItalianPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.tw/pg/brochure/v4/?p=.
        /// </summary>
        internal static string TaiwanPgUrl {
            get {
                return ResourceManager.GetString("TaiwanPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.co.th/pg/brochure/v4/?p=.
        /// </summary>
        internal static string ThaiPgUrl {
            get {
                return ResourceManager.GetString("ThaiPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.tn/fp/brochure/v4/?p=.
        /// </summary>
        internal static string TunesiaPgUrl {
            get {
                return ResourceManager.GetString("TunesiaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.tr/pg/brochure/v4/?p=.
        /// </summary>
        internal static string TurkeyPgUrl {
            get {
                return ResourceManager.GetString("TurkeyPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com/pg/brochure/v4/?p=.
        /// </summary>
        internal static string UnitedArabEmiratesEnglishPgUrl {
            get {
                return ResourceManager.GetString("UnitedArabEmiratesEnglishPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.co.ae/pg/brochure/v4/?p=.
        /// </summary>
        internal static string UnitedArabEmiratesPgUrl {
            get {
                return ResourceManager.GetString("UnitedArabEmiratesPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.co.uk/pg/brochure/v4/?p=.
        /// </summary>
        internal static string UnitedKingdomPgUrl {
            get {
                return ResourceManager.GetString("UnitedKingdomPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.edu/pg/brochure/v4/?p=.
        /// </summary>
        internal static string UnitedStatesPgUrl {
            get {
                return ResourceManager.GetString("UnitedStatesPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.uy/pg/brochure/v4/?p=.
        /// </summary>
        internal static string UruguayPgUrl {
            get {
                return ResourceManager.GetString("UruguayPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.co.ve/pg/brochure/v4/?p=.
        /// </summary>
        internal static string VenezuelaPgUrl {
            get {
                return ResourceManager.GetString("VenezuelaPgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qa.ef.com.vn/pg/brochure/v4/?p=.
        /// </summary>
        internal static string VietnamPgUrl {
            get {
                return ResourceManager.GetString("VietnamPgUrl", resourceCulture);
            }
        }
    }
}
