//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePGTrackingSwitzerlandCS_TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePGTrackingSwitzerlandCS_TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rentals.Resources.ResourcePGTrackingSwitzerlandCS_TestData", typeof(ResourcePGTrackingSwitzerlandCS_TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cs.
        /// </summary>
        internal static string c1 {
            get {
                return ResourceManager.GetString("c1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007920.
        /// </summary>
        internal static string c10 {
            get {
                return ResourceManager.GetString("c10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string c17 {
            get {
                return ResourceManager.GetString("c17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pc.
        /// </summary>
        internal static string c20 {
            get {
                return ResourceManager.GetString("c20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pg:auslandsaufenthalt.
        /// </summary>
        internal static string c21 {
            get {
                return ResourceManager.GetString("c21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pg:auslandsaufenthalt:all.
        /// </summary>
        internal static string c22 {
            get {
                return ResourceManager.GetString("c22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.efswiss.ch/de/pg/auslandsaufenthalt/.
        /// </summary>
        internal static string c25 {
            get {
                return ResourceManager.GetString("c25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New:pg:auslandsaufenthalt:all:all:all:all:all.
        /// </summary>
        internal static string c27 {
            get {
                return ResourceManager.GetString("c27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pg.
        /// </summary>
        internal static string c3 {
            get {
                return ResourceManager.GetString("c3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dtm-new.
        /// </summary>
        internal static string c37 {
            get {
                return ResourceManager.GetString("c37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8:ilc,ils,ilsp,ly,hsy,ia,hult,ap.
        /// </summary>
        internal static string c39 {
            get {
                return ResourceManager.GetString("c39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to efswiss.ch.
        /// </summary>
        internal static string c4 {
            get {
                return ResourceManager.GetString("c4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google organic.
        /// </summary>
        internal static string c5 {
            get {
                return ResourceManager.GetString("c5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ns_ggch_web.
        /// </summary>
        internal static string c7 {
            get {
                return ResourceManager.GetString("c7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pageName&quot;:&quot;pg:auslandsaufenthalt:all:all:all:all:all&quot;,&quot;g&quot;:&quot;http://www.efswiss.ch/de/pg/auslandsaufenthalt/&quot;,
        ///&quot;c1&quot;:&quot;cs&quot;,
        ///&quot;c3&quot;:&quot;pg&quot;,
        ///&quot;c4&quot;:&quot;efswiss.ch&quot;,
        ///&quot;c5&quot;:&quot;google organic&quot;,
        ///&quot;c7&quot;:&quot;ns_ggch_web&quot;,
        ///&quot;c10&quot;:&quot;007920&quot;,
        ///&quot;c17&quot;:&quot;New&quot;,
        ///&quot;c20&quot;:&quot;pc&quot;,
        ///&quot;c21&quot;:&quot;pg:auslandsaufenthalt&quot;,
        ///&quot;c22&quot;:&quot;pg:auslandsaufenthalt:all&quot;,
        ///&quot;c25&quot;:&quot;http://www.efswiss.ch/de/pg/auslandsaufenthalt/&quot;,
        ///&quot;c27&quot;:&quot;New:pg:auslandsaufenthalt:all:all:all:all:all&quot;,
        ///&quot;c37&quot;:&quot;dtm-new&quot;,
        ///&quot;c39&quot;:&quot;8:ilc,ils,ilsp,ly,hsy,ia,hult,ap&quot;}.
        /// </summary>
        internal static string CaseThirdDTMExpectedResult {
            get {
                return ResourceManager.GetString("CaseThirdDTMExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;SourceCode&quot;: &quot;007920&quot;,&quot;Partner&quot;: &quot;google organic&quot;,&quot;Etag&quot;: &quot;ns_ggch_web&quot;}.
        /// </summary>
        internal static string CaseThirdMinervaExpectedResult {
            get {
                return ResourceManager.GetString("CaseThirdMinervaExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://efeducation.d1.sc.omtrdc.net/b/ss/efefcom-global/1.
        /// </summary>
        internal static string FiddlerDTMVerification {
            get {
                return ResourceManager.GetString("FiddlerDTMVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.efswiss.ch/ef-services/svc-lb/tracking/minerva.
        /// </summary>
        internal static string FiddlerMinerva {
            get {
                return ResourceManager.GetString("FiddlerMinerva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.efswiss.ch/de/pg/auslandsaufenthalt/.
        /// </summary>
        internal static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pg:auslandsaufenthalt:all:all:all:all:all.
        /// </summary>
        internal static string pageName {
            get {
                return ResourceManager.GetString("pageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUSLANDSAUFENTHALT ef pg.
        /// </summary>
        internal static string SearchData {
            get {
                return ResourceManager.GetString("SearchData", resourceCulture);
            }
        }
    }
}
